{{- if not .Values.secret.existing }}
apiVersion: v1
kind: Secret

metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hcloud-csi-mgmt.labels" . | nindent 4 }}

type: Opaque
data:
  hcloud: {{ .Values.secret.token | b64enc }}
{{- end }}
