apiVersion: v1
kind: Service

metadata:
  name: {{ template "yopass.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yopass.labels" . | nindent 4 }}
{{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
{{- end }}
{{- if  .Values.service.annotations }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}

spec:
  type: {{ .Values.service.type }}

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}

  selector:
    {{- include "yopass.selectorLabels" . | nindent 4 }}
