{{- if and (not .Values.ldap.existingSecret) (.Values.ldap.enable) }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "ansible-semaphore.fullname" . }}-ldap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansible-semaphore.labels" . | nindent 4 }}
{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

type: Opaque
data:
  {{ .Values.ldap.binddnKey }}: {{ .Values.ldap.binddn | b64enc }}
  {{ .Values.ldap.passwordKey }}: {{ .Values.ldap.password | b64enc }}
{{- end }}
