{{- if and (not .Values.database.existingSecret) (ne .Values.database.type "bolt") }}
---
apiVersion: v1
kind: Secret

metadata:
  name: {{ include "ansible-semaphore.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ansible-semaphore.labels" . | nindent 4 }}
{{- if .Values.labels }}
    {{- toYaml .Values.labels | nindent 4 }}
{{- end }}
{{- if  .Values.annotations }}
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
{{- end }}

type: Opaque
data:
  {{ .Values.database.usernameKey }}: {{ .Values.database.username | b64enc }}
  {{ .Values.database.passwordKey }}: {{ .Values.database.password | b64enc }}
{{- end }}
