annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Source
      url: https://github.com/ansible-semaphore/semaphore
    - name: Chart
      url: https://github.com/cloudhippie/charts/tree/master/stable/ansible-semaphore
  artifacthub.io/signKey: |
    fingerprint: 2B62F542C0C5614F8B4625AE0DDA0DEB51EF789C
    url: https://raw.githubusercontent.com/cloudhippie/charts/master/cloudhippie.key
apiVersion: v2
appVersion: 2.9.64
dependencies:
- condition: mariadb.enabled
  name: mariadb
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.0.1
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 16.2.0
description: Modern and open-source alternative to AWX/Tower
home: https://semaphoreui.com/
icon: https://raw.githubusercontent.com/ansible-semaphore/semaphore/develop/web/public/favicon.svg
keywords:
- ansible
- awx
- tower
maintainers:
- email: thomas@webhippie.de
  name: tboerger
  url: https://github.com/tboerger
name: ansible-semaphore
sources:
- https://github.com/ansible-semaphore/semaphore
type: application
version: 9.0.0
