annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |-
    - name: Source
      url: https://github.com/jhaals/yopass
    - name: Chart
      url: https://github.com/cloudhippie/charts/tree/master/stable/yopass
  artifacthub.io/signKey: |
    fingerprint: 12B3EDFEA2ACC1EA3D29511981ACD5B5DF2DBDAA
    url: https://raw.githubusercontent.com/cloudhippie/charts/master/cloudhippie.key
apiVersion: v2
appVersion: 11.15.1
dependencies:
- condition: redis.enabled
  name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 18.6.4
- condition: memcached.enabled
  name: memcached
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 6.7.4
description: Secure sharing of secrets, passwords and files
home: https://yopass.se/
icon: https://raw.githubusercontent.com/jhaals/yopass/master/logo/yopass.svg
keywords:
- password
- secret
- sharing
maintainers:
- email: thomas@webhippie.de
  name: tboerger
  url: https://github.com/tboerger
name: yopass
sources:
- https://github.com/jhaals/yopass
type: application
version: 1.7.5
