---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: helmdocs

"on":
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  helmdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Setup nodejs
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Generate token
        id: token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.TOKEN_EXCHANGE_APP }}
          private-key: ${{ secrets.TOKEN_EXCHANGE_KEY }}
          permission-contents: write

      - name: Checkout source
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ steps.token.outputs.token }}

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Update readme
        run: helm-docs

      - name: Source rebase
        run: git pull --autostash --rebase

      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        with:
          author_name: GitHub Actions
          author_email: github@cloudhippie.de
          add: stable/
          message: "docs: automated readme update [skip ci]"
          push: true
          commit: --signoff

...

