---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: release

"on":
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Git author
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github@cloudhippie.de"

      - name: Update readme
        run: helm-docs

      - name: Write secring
        run: |
          echo -n "${{ secrets.GNUPG_SECRING }}" \
            | base64 --decode \
            > secring.gpg

      - name: Write passphrase
        run: |
          echo -n "${{ secrets.GNUPG_PASSWORD }}" \
            > passphrase

      - name: Run releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_KEYRING: secring.gpg
          CR_PASSPHRASE_FILE: passphrase
        with:
          config: cr.yaml
          charts_dir: stable

      - name: Push charts
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login --username cloudhippiez --password-stdin ghcr.io

          if test -d .cr-release-packages; then
            for pkg in .cr-release-packages/*.tgz; do
              if [ -z "${pkg:-}" ]; then
                break
              fi

              echo "Pushing $pkg..."
              helm push "$pkg" "oci://ghcr.io/$GITHUB_REPOSITORY_OWNER/charts"
            done
          fi

      - name: Remove secrets
        if: always()
        run: |
          rm -f secring.gpg passphrase

...
